export type KkiapayTransactionType = {
  received_at: number,
  type: 'DEBIT' | 'CREDIT',
  status: 'SUCCESS' | 'FAILED' | 'INSUFFICIENT_FUND' | 'TRANSACTION_NOT_ELIGIBLE' | 'TRANSACTION_NOT_FOUND' | 'INVALID_TRANSACTION' | 'INVALID_TRANSACTION_TYPE' | 'INVALID_PAYOUT_DESTINATION_ACCOUNT',
  source: 'MOBILE_MONEY' | 'BANK_ACCOUNT',
  source_common_name: string,
  amount: number,
  fees: number,
  isFeesBorneByMerchant: boolean,
  net: number,
  paymentlink: string | null,
  country: string, // ex: 'BJ'
  reason: string,
  state: string,
  partnerId: string,
  before_balance: number,
  after_balance: number,
  is_payout: boolean,
  is_counted: boolean,
  wallet: 'payout-wallet' | 'payin-wallet',
  sharedTransaction: null,
  client: {
    meta_data: string,
    isNewGeneration: true,
    fullname: string,
    country: string,
    phone: string,
    email: string,
    account: null,
    person: null
  },
  session: string | null,
  transactionId: string,
  performedAt: string,
};