export const AdminPermission = {
  DASHBOARD: "tableau_de_bord",
  USERS: "utilisateurs",
  ORDERS: "commandes",
  APPOINTMENTS: "rendez_vous",
  PRODUCTS: "produits",
  SUPER_CATEGORIES_PRODUCTS: "super_categories_produits",
  ACCESSORY_CATEGORIES: "categories_d_accessoires",
  GLASS_SIZES: "tailles_des_lunettes",
  FRAMES: "montures",
  BRANDS: "marques",
  SHOPS: "boutiques",
  BANNER_TEXTS: "texte_defilant",
  IMAGE_CAROUSEL: "carousel_d_image",
  POPUPS: "popups",
  DELIVERY_METHODS: "mode_de_livraison",
  OFFERS: "offres",
  NEWS: "actualites",
  EVENTS: "evenements",
  SERVICES: "services",
  PARTNERS: "partenaires",
  TESTIMONIALS: "temoignages",
  FAQS: "faqs",
  ADMINS: "administrateurs",
  SETTINGS: "parametres",
  COMMENTAIRES: "commentaires",
} as const;
