export enum Status {
    // Généraux (0+)
    INACTIVE = 0,
    ACTIVE = 1,
    PENDING = 2,
    ARCHIVED = 3,
    DELETED = 4,
    DRAFT = 5,
    VISIBLE = 6,
    HIDDEN = 7,
    LOCKED = 8,
    UNLOCKED = 9,
    EDITING = 10,
    PUBLISHED = 11,
    UNPUBLISHED = 12,
    PENDING_VALIDATION = 13,
    BANNED = 14,
    UNBANNED = 15,
    SUSPENDED = 16,
    UNSUSPENDED = 17,
    TERMINATED = 18,
    UNTERMINATED = 19,
    CANCELED = 20,
    UNCANCELLED = 21,
    REJECTED = 22,
    APPROVED = 23,
    PENDING_PAYMENT = 24,
    PAID = 25,
    REFUNDED = 26,
    FAILED = 27,
    DELIVERED = 28,
    CANCELLED = 29,
    EXPIRED = 30,
    IN_PROGRESS = 31,
    COMPLETED = 32,
    DELAYED = 33,
    BLOCKED = 34,
    UNBLOCKED = 35,
    BOOKED = 36,

    //Appointments (40+)
    APPOINTMENT_PENDING_PAYMENT = 40,
    APPOINTMENT_PAID = 41,
    APPOINTMENT_CANCELLED = 42,
    APPOINTMENT_BOOKED = 43,
    APPOINTMENT_COMPLETED = 44,

    //Utilisateurs (100+)
    USER_ACTIVE = 100,
    USER_INACTIVE = 101,
    USER_BANNED = 102,
    USER_PENDING_VALIDATION = 103,
    USER_DELETED = 104,

    // Commandes (200+)
    ORDER_PENDING = 200,
    ORDER_PAID = 201,
    ORDER_CANCELLED = 202,
    ORDER_DELIVERED = 203,
    ORDER_REFUNDED = 204,
    ORDER_FAILED = 205,

    // Paiements (300+)
    PAYMENT_PENDING = 300,
    PAYMENT_SUCCESS = 301,
    PAYMENT_FAILED = 302,
    PAYMENT_REFUNDED = 303,
    PAYMENT_CANCELLED = 304,
    PAYMENT_EXPIRED = 305,

    // Produits (400+)
    PRODUCT_ACTIVE = 400,
    PRODUCT_INACTIVE = 401,
    PRODUCT_OUT_OF_STOCK = 402,
    PRODUCT_DISCONTINUED = 403,

    // Employés (500+)
    EMPLOYEE_ACTIVE = 500,
    EMPLOYEE_INACTIVE = 501,
    EMPLOYEE_SUSPENDED = 502,
    EMPLOYEE_TERMINATED = 503,

    // Tâches / Processus (600+)
    TASK_PENDING = 600,
    TASK_IN_PROGRESS = 601,
    TASK_COMPLETED = 602,
    TASK_FAILED = 603,
    TASK_CANCELLED = 604,

    // Notifications (700+)
    NOTIFICATION_UNREAD = 700,
    NOTIFICATION_READ = 701,
    NOTIFICATION_ARCHIVED = 702,
}
